import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  // Create categories
  const categories = await Promise.all([
    prisma.category.upsert({
      where: { slug: 'alkitab' },
      update: {},
      create: {
        name: 'Alkitab',
        slug: 'alkitab',
        description: 'Berbagai versi dan terjemahan Alkitab',
        image: 'https://loremflickr.com/400/400/bible',
      },
    }),
    prisma.category.upsert({
      where: { slug: 'buku-katolik' },
      update: {},
      create: {
        name: 'Buku Katolik',
        slug: 'buku-katolik',
        description: 'Buku-buku khusus untuk umat Katolik',
        image: 'https://loremflickr.com/400/400/church',
      },
    }),
    prisma.category.upsert({
      where: { slug: 'renungan' },
      update: {},
      create: {
        name: 'Renungan',
        slug: 'renungan',
        description: 'Buku renungan harian dan rohani',
        image: 'https://loremflickr.com/400/400/prayer',
      },
    }),
    prisma.category.upsert({
      where: { slug: 'teologi' },
      update: {},
      create: {
        name: 'Teologi',
        slug: 'teologi',
        description: 'Buku-buku teologi dan studi Alkitab',
        image: 'https://loremflickr.com/400/400/books',
      },
    }),
    prisma.category.upsert({
      where: { slug: 'kids' },
      update: {},
      create: {
        name: 'Anak-Anak',
        slug: 'kids',
        description: 'Buku cerita dan aktivitas untuk anak-anak',
        image: 'https://loremflickr.com/400/400/children',
      },
    }),
    prisma.category.upsert({
      where: { slug: 'musik-pujian' },
      update: {},
      create: {
        name: 'Musik & Pujian',
        slug: 'musik-pujian',
        description: 'Buku lagu, not balok, dan musik pujian',
        image: 'https://loremflickr.com/400/400/music',
      },
    }),
    prisma.category.upsert({
      where: { slug: 'pernikahan-keluarga' },
      update: {},
      create: {
        name: 'Pernikahan & Keluarga',
        slug: 'pernikahan-keluarga',
        description: 'Buku tentang pernikahan Kristen dan keluarga',
        image: 'https://loremflickr.com/400/400/family',
      },
    }),
    prisma.category.upsert({
      where: { slug: 'rohaniwan' },
      update: {},
      create: {
        name: 'Rohaniwan',
        slug: 'rohaniwan',
        description: 'Buku untuk pendeta, imam, dan pelayan gereja',
        image: 'https://loremflickr.com/400/400/priest',
      },
    }),
  ]);

  console.log('Categories created:', categories.length);

  // Create sample books
  const booksData = [
    // Alkitab
    {
      title: 'Alkitab Terjemahan Baru (TB)',
      slug: 'alkitab-tb',
      author: 'Lembaga Alkitab Indonesia',
      description: 'Alkitab Terjemahan Baru adalah terjemahan Alkitab dalam bahasa Indonesia yang diterbitkan oleh Lembaga Alkitab Indonesia. Terjemahan ini merupakan hasil revisi dari Terjemahan Lama yang diterbitkan pada tahun 1958.',
      price: 125000,
      coverImage: 'https://loremflickr.com/400/500/bible,religious',
      isbn: '978-979-463-000-1',
      publisher: 'Lembaga Alkitab Indonesia',
      publishYear: 2020,
      pages: 1500,
      stock: 50,
      isFeatured: true,
      isBestseller: true,
      categoryId: categories[0].id,
    },
    {
      title: 'Alkitab Bahasa Indonesia Sehari-hari (BIS)',
      slug: 'alkitab-bis',
      author: 'Lembaga Alkitab Indonesia',
      description: 'Alkitab dalam bahasa Indonesia yang mudah dipahami untuk pembaca modern. Cocok untuk renungan harian dan studi Alkitab.',
      price: 145000,
      discountPrice: 125000,
      coverImage: 'https://loremflickr.com/400/500/bible,scripture',
      isbn: '978-979-463-001-8',
      publisher: 'Lembaga Alkitab Indonesia',
      publishYear: 2021,
      pages: 1420,
      stock: 35,
      isFeatured: true,
      isNew: true,
      categoryId: categories[0].id,
    },
    {
      title: 'Alkitab Deuterokanonika Katolik',
      slug: 'alkitab-deuterokanonika',
      author: 'Lembaga Alkitab Indonesia',
      description: 'Alkitab lengkap dengan kitab-kitab Deuterokanonika untuk umat Katolik. Terjemahan resmi dari Lembaga Alkitab Indonesia.',
      price: 185000,
      coverImage: 'https://loremflickr.com/400/500/catholic,bible',
      isbn: '978-979-463-002-5',
      publisher: 'Lembaga Alkitab Indonesia',
      publishYear: 2019,
      pages: 1680,
      stock: 25,
      isBestseller: true,
      categoryId: categories[0].id,
    },
    // Buku Katolik
    {
      title: 'Katekismus Gereja Katolik',
      slug: 'katekismus-gereja-katolik',
      author: 'Konferensi Waligereja Indonesia',
      description: 'Katekismus Gereja Katolik adalah eksposisi iman Gereja Katolik dan ajaran gereja yang disajikan secara sistematis.',
      price: 275000,
      coverImage: 'https://loremflickr.com/400/500/church,catholic',
      isbn: '978-979-451-123-4',
      publisher: 'Obor Indonesia',
      publishYear: 2018,
      pages: 890,
      stock: 20,
      isFeatured: true,
      isBestseller: true,
      categoryId: categories[1].id,
    },
    {
      title: 'Doa-doa Harian Katolik',
      slug: 'doa-harian-katolik',
      author: 'P. D. S. P. Sugiharto',
      description: 'Kumpulan doa harian untuk umat Katolik, termasuk Rosario, Jalan Salib, dan doa-doa liturgi.',
      price: 45000,
      discountPrice: 38000,
      coverImage: 'https://loremflickr.com/400/500/prayer,rosary',
      isbn: '978-979-451-124-1',
      publisher: 'Kanisius',
      publishYear: 2022,
      pages: 180,
      stock: 100,
      isBestseller: true,
      categoryId: categories[1].id,
    },
    {
      title: 'Mengenal Santo dan Santa Pelindung',
      slug: 'santo-santa-pelindung',
      author: 'Alb. Soegijapranata',
      description: 'Buku panduan lengkap mengenal para Santo dan Santa pelindung dalam tradisi Katolik.',
      price: 85000,
      coverImage: 'https://loremflickr.com/400/500/saint,saints',
      isbn: '978-979-451-125-8',
      publisher: 'Kanisius',
      publishYear: 2020,
      pages: 256,
      stock: 45,
      isNew: true,
      categoryId: categories[1].id,
    },
    // Renungan
    {
      title: 'Santapan Harian 2024',
      slug: 'santapan-harian-2024',
      author: 'Yayasan Persekutuan Pembaca Alkitab',
      description: 'Renungan harian untuk setiap hari dalam setahun. Membantu Anda mendekatkan diri kepada Tuhan melalui firman-Nya.',
      price: 75000,
      discountPrice: 65000,
      coverImage: 'https://loremflickr.com/400/500/devotion,daily',
      isbn: '978-979-432-001-2',
      publisher: 'YPPA',
      publishYear: 2024,
      pages: 400,
      stock: 150,
      isFeatured: true,
      isBestseller: true,
      isNew: true,
      categoryId: categories[2].id,
    },
    {
      title: 'Our Daily Bread 2024',
      slug: 'our-daily-bread-2024',
      author: 'RBC Ministries',
      description: 'Renungan harian Our Daily Bread dalam bahasa Indonesia. Diterbitkan oleh RBC Ministries.',
      price: 55000,
      coverImage: 'https://loremflickr.com/400/500/daily,bread',
      isbn: '978-979-432-002-9',
      publisher: 'RBC Ministries Indonesia',
      publishYear: 2024,
      pages: 380,
      stock: 200,
      isBestseller: true,
      categoryId: categories[2].id,
    },
    {
      title: 'Renungan Pagi Soren',
      slug: 'renungan-pagi-soren',
      author: 'Yayasan Scripture Union Indonesia',
      description: 'Renungan pagi dan sore untuk memulai dan mengakhiri hari dengan firman Tuhan.',
      price: 65000,
      coverImage: 'https://loremflickr.com/400/500/morning,prayer',
      isbn: '978-979-432-003-6',
      publisher: 'Scripture Union Indonesia',
      publishYear: 2024,
      pages: 420,
      stock: 80,
      isNew: true,
      categoryId: categories[2].id,
    },
    // Teologi
    {
      title: 'Teologi Sistematis: Pengantar',
      slug: 'teologi-sistematis',
      author: 'Wayne Grudem',
      description: 'Buku teologi sistematis yang komprehensif untuk memahami ajaran-ajaran Kristen secara mendalam.',
      price: 350000,
      discountPrice: 299000,
      coverImage: 'https://loremflickr.com/400/500/theology,books',
      isbn: '978-979-291-001-4',
      publisher: 'Momentum',
      publishYear: 2017,
      pages: 1250,
      stock: 15,
      isFeatured: true,
      categoryId: categories[3].id,
    },
    {
      title: 'Dasar-Dasar Teologi Kristen',
      slug: 'dasar-teologi-kristen',
      author: 'Millard J. Erickson',
      description: 'Pengantar teologi Kristen yang komprehensif dan mudah dipahami.',
      price: 285000,
      coverImage: 'https://loremflickr.com/400/500/christian,theology',
      isbn: '978-979-291-002-1',
      publisher: 'BPK Gunung Mulia',
      publishYear: 2019,
      pages: 980,
      stock: 20,
      categoryId: categories[3].id,
    },
    // Anak-Anak
    {
      title: 'Cerita Alkitab untuk Anak',
      slug: 'cerita-alkitab-anak',
      author: 'Sally Lloyd-Jones',
      description: 'Kumpulan cerita Alkitab yang indah untuk anak-anak dengan ilustrasi yang menarik.',
      price: 125000,
      discountPrice: 99000,
      coverImage: 'https://loremflickr.com/400/500/children,bible',
      isbn: '978-979-541-001-7',
      publisher: 'GRAFINDO',
      publishYear: 2022,
      pages: 350,
      stock: 60,
      isFeatured: true,
      isBestseller: true,
      categoryId: categories[4].id,
    },
    {
      title: 'Aktivitas Alkitab Anak',
      slug: 'aktivitas-alkitab-anak',
      author: 'Tim Gloria Publisher',
      description: 'Buku aktivitas dengan mewarnai, teka-teki silang, dan permainan berdasarkan cerita Alkitab.',
      price: 45000,
      coverImage: 'https://loremflickr.com/400/500/kids,activity',
      isbn: '978-979-541-002-4',
      publisher: 'Gloria Publisher',
      publishYear: 2023,
      pages: 64,
      stock: 120,
      isNew: true,
      categoryId: categories[4].id,
    },
    // Musik & Pujian
    {
      title: 'Nyanyian Pujian (NP) Lengkap',
      slug: 'nyanyian-pujian-lengkap',
      author: 'Majelis Sinode Gereja Kristen',
      description: 'Buku nyanyian pujian lengkap dengan not balok untuk ibadah gereja.',
      price: 95000,
      coverImage: 'https://loremflickr.com/400/500/hymn,music',
      isbn: '978-979-621-001-0',
      publisher: 'BPK Gunung Mulia',
      publishYear: 2020,
      pages: 450,
      stock: 75,
      isBestseller: true,
      categoryId: categories[5].id,
    },
    {
      title: 'Kidung Jemaat (KJ) Edisi Baru',
      slug: 'kidung-jemaat-edisi-baru',
      author: 'Tim Lembaga Musik Gereja',
      description: 'Buku Kidung Jemaat edisi terbaru dengan lagu-lagu pujian untuk ibadah.',
      price: 85000,
      coverImage: 'https://loremflickr.com/400/500/worship,songs',
      isbn: '978-979-621-002-7',
      publisher: 'BPK Gunung Mulia',
      publishYear: 2021,
      pages: 420,
      stock: 90,
      categoryId: categories[5].id,
    },
    // Pernikahan & Keluarga
    {
      title: 'Membangun Keluarga Kristen',
      slug: 'membangun-keluarga-kristen',
      author: 'Gary Chapman',
      description: 'Panduan membangun keluarga Kristen yang kuat dan harmonis.',
      price: 78000,
      discountPrice: 68000,
      coverImage: 'https://loremflickr.com/400/500/family,christian',
      isbn: '978-979-711-001-3',
      publisher: 'Gramedia Pustaka Utama',
      publishYear: 2021,
      pages: 280,
      stock: 55,
      isBestseller: true,
      categoryId: categories[6].id,
    },
    {
      title: '5 Bahasa Kasih',
      slug: '5-bahasa-kasih',
      author: 'Gary Chapman',
      description: 'Buku terlaris tentang cara mengekspresikan cinta dalam 5 bahasa kasih yang berbeda.',
      price: 85000,
      coverImage: 'https://loremflickr.com/400/500/love,marriage',
      isbn: '978-979-711-002-0',
      publisher: 'Gramedia Pustaka Utama',
      publishYear: 2020,
      pages: 220,
      stock: 70,
      isFeatured: true,
      isBestseller: true,
      categoryId: categories[6].id,
    },
    // Rohaniwan
    {
      title: 'Panduan Homiletika',
      slug: 'panduan-homiletika',
      author: 'Haddon W. Robinson',
      description: 'Panduan praktis untuk mempersiapkan dan menyampaikan khotbah yang efektif.',
      price: 165000,
      coverImage: 'https://loremflickr.com/400/500/preaching,ministry',
      isbn: '978-979-811-001-8',
      publisher: 'Momentum',
      publishYear: 2019,
      pages: 350,
      stock: 25,
      categoryId: categories[7].id,
    },
    {
      title: 'Pelayanan Pastoral',
      slug: 'pelayanan-pastoral',
      author: 'Thomas C. Oden',
      description: 'Buku referensi lengkap tentang pelayanan pastoral bagi para pendeta dan rohaniwan.',
      price: 225000,
      coverImage: 'https://loremflickr.com/400/500/pastor,ministry',
      isbn: '978-979-811-002-5',
      publisher: 'BPK Gunung Mulia',
      publishYear: 2018,
      pages: 520,
      stock: 18,
      isFeatured: true,
      categoryId: categories[7].id,
    },
  ];

  for (const book of booksData) {
    await prisma.book.upsert({
      where: { slug: book.slug },
      update: book,
      create: book,
    });
  }

  console.log('Books created:', booksData.length);

  // Create banners
  const banners = await Promise.all([
    prisma.banner.upsert({
      where: { id: 'banner-1' },
      update: {},
      create: {
        id: 'banner-1',
        title: 'Selamat Datang di Toko Buku Gloria',
        subtitle: 'Toko buku Kristen terlengkap dengan koleksi Alkitab, buku Katolik, dan renungan harian',
        image: 'https://loremflickr.com/1200/450/bible,bookstore',
        link: '/?category=alkitab',
        isActive: true,
        order: 1,
      },
    }),
    prisma.banner.upsert({
      where: { id: 'banner-2' },
      update: {},
      create: {
        id: 'banner-2',
        title: 'Koleksi Alkitab Terbaru',
        subtitle: 'Temukan berbagai versi Alkitab untuk kebutuhan rohani Anda',
        image: 'https://loremflickr.com/1200/450/scripture,church',
        link: '/?category=alkitab',
        isActive: true,
        order: 2,
      },
    }),
    prisma.banner.upsert({
      where: { id: 'banner-3' },
      update: {},
      create: {
        id: 'banner-3',
        title: 'Santapan Harian 2024',
        subtitle: 'Renungan harian untuk setiap hari dalam setahun',
        image: 'https://loremflickr.com/1200/450/prayer,devotion',
        link: '/?book=santapan-harian-2024',
        isActive: true,
        order: 3,
      },
    }),
  ]);

  console.log('Banners created:', banners.length);

  console.log('Seed completed successfully!');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
